Backfill Changelog Entries per-PR
embroider-build/embroider pull request #1360
Opened 2023-02-14 19:54 UTC by NullVoxPopuli

_This PR determines what semver increment each package should have upon release_

Once merged (after agreeing on the changelog entries, and severity of the changes), a "Release preview PR" will be opened by github-actions, so we can see how the changes propagate across the different packages in the monorepo.

----------------------------

Done with:
```
pnpx changeset-recover@beta -b 8db1b27dfa3707058803104abc92387d570abb6c
```
where 8db1b27dfa3707058803104abc92387d570abb6c is the commit of the last release (changeset-recover will use the last tag, if it exists -- but in this case, the last tag was a while ago, so changeset-recover initially included too much stuff).

After interacting with the prompt, I confirmed with:
![image](https://user-images.githubusercontent.com/199018/218846486-38516e9e-160b-4e36-a6a6-1e729cbc221c.png)

2023-04-18 15:51 UTC, mansona requested changes
Firstly great work on the automation here 🎉  This isn't really ready for merging because the changes need manual refinement i.e. a human needs to go through each file and edit it to be more descriptive 👍

2023-04-18 15:55 UTC, NullVoxPopuli commented on .changeset/automated-from-c2dd82ec06831a846c3d7d7e47261a04b2b4f6a3.md
> +"@embroider/compat": TODO
patch

2023-04-18 15:55 UTC, NullVoxPopuli commented on .changeset/automated-from-c2dd82ec06831a846c3d7d7e47261a04b2b4f6a3.md
> +"@embroider/core": TODO
remove, https://github.com/embroider-build/embroider/pull/1340/files#diff-a5cbba44c120a6bcfc99a5a7fe32bc73be243236913f8060889d56a02e4a79ff does not change this package, and changesets will bump consumers appropriately

2023-04-18 15:55 UTC, NullVoxPopuli commented on .changeset/automated-from-c2dd82ec06831a846c3d7d7e47261a04b2b4f6a3.md
> +"@embroider/webpack": TODO
remove, per above

2023-04-19 04:32 UTC, NullVoxPopuli commented
Closing in favor of https://github.com/embroider-build/embroider/pull/1398

2023-04-19 04:32 UTC, closed without merging