vite also needs to resolve index.{gjs,gts}
embroider-build/embroider pull request #1826
Opened 2024-02-29 10:57 UTC by patricklx

2024-02-29 11:36 UTC, mansona requested changes
This will likely be fixed by https://github.com/embroider-build/embroider/pull/1794, or at the very least we should add a failing test somewhere after that is merged before we make any more changes like this 👍

2024-02-29 12:00 UTC, patricklx commented on tests/vite-app/app/components/fancy.gts
> +import WithIndex from './with-index';
this is the import that would fail to resolve

2024-02-29 13:47 UTC, patricklx commented
one test failed while fetching node...

2024-03-05 15:34 UTC, ef4 commented
Idea here is that we should try switching at least the gjs/gts support to rely on vote's own resolve-extensions, so that it composes with vite's built-in index search.

We may or may not be able to do that for hbs given that within app code the hbs support is more complex, given the existence of template-only components, etc.

2024-03-13 09:41 UTC, patricklx commented
somehow after adding the extensions to resolve.
the module-resolver resolveComponent is receiving `type: ignore` results...

2024-03-27 14:35 UTC, patricklx commented
the last commit makes esbuild resolver behave the same as vite, when we have a `not-found` we report it as external.
now another issue:
all imports that are resolved via `resolveWithinMovedPackage` do not get dep optimization, because the importer is in node_modules. this causes the vite app to use duplicate modules @ef4

2024-04-02 13:00 UTC, patricklx commented
2 issues:
* resolveWithinMovedPackage changes importer to be in node-modules, which makes vite/esbuild ignore it.
1. solution: generate links to rewritten-packages that are resolvable via node resolution and just rewrite the request specifier
2. Change the specifier to a special prefix that will be treated specially? How?

* virtual modules start with a prefix, which changes all its imports to /fs/... full path. Can be fixed by using a suffix instead.

2024-04-02 15:42 UTC, ef4 commented
I think this is going to need pairing at office hours to sort through. Changing from prefix to suffix seems like a workaround for what is actually breaking.

2024-04-04 14:01 UTC, patricklx commented
<img width="1199" alt="Screenshot 2024-04-04 at 16 00 51" src="https://github.com/embroider-build/embroider/assets/1332320/259c560c-8fed-41fa-8abf-f99bfe61f796">

2024-07-13 19:48 UTC, patricklx commented
will be fixed by #2029

2024-07-13 19:48 UTC, closed without merging